hl.on("hyprland.start", function()
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1")
    hl.exec_cmd("qs")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hyprctl setcursor Bibata-Modern-Classic 22")
    hl.exec_cmd("udiskie")
    hl.exec_cmd("hypridle")
	hl.exec_cmd("while true; do ~/.local/bin/battery.sh --notify; sleep 60; done &")
end)
